# Generated by Django 3.2.4 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('temp', models.CharField(max_length=10, null=True)),
                ('feels_like', models.CharField(max_length=45, null=True)),
                ('temp_min', models.CharField(max_length=45, null=True)),
                ('temp_max', models.CharField(max_length=45, null=True)),
                ('pressure', models.CharField(max_length=45, null=True)),
                ('humidity', models.CharField(max_length=45, null=True)),
                ('wind_speed', models.CharField(max_length=45, null=True)),
                ('wind_deg', models.CharField(max_length=45, null=True)),
                ('clouds_all', models.CharField(max_length=45, null=True)),
                ('weather_main', models.CharField(max_length=45, null=True)),
                ('weather_description', models.CharField(max_length=45, null=True)),
                ('weather_icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastWeather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dt_iso', models.CharField(max_length=45, null=True)),
                ('temp', models.CharField(max_length=45, null=True)),
                ('temp_min', models.CharField(max_length=45, null=True)),
                ('temp_max', models.CharField(max_length=45, null=True)),
                ('pressure', models.CharField(max_length=45, null=True)),
                ('humidity', models.CharField(max_length=45, null=True)),
                ('wind_speed', models.CharField(max_length=45, null=True)),
                ('wind_deg', models.CharField(max_length=45, null=True)),
                ('clouds_all', models.CharField(max_length=45, null=True)),
                ('weather_id', models.CharField(max_length=45, null=True)),
                ('weather_main', models.CharField(max_length=45, null=True)),
                ('weather_description', models.CharField(max_length=45, null=True)),
                ('weather_icon', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
