# Generated by Django 3.2.4 on 2021-07-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_number_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=45, null=True)),
                ('route_description', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=45, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllStopsWithRoute',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('stop_sequence', models.CharField(max_length=10, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
                ('route_number_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.routes')),
                ('stop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stops')),
            ],
        ),
    ]
