# Generated by Django 3.2.4 on 2021-07-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_allstopswithroute_routes_stops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstopswithroute',
            old_name='route_number_id',
            new_name='route_number',
        ),
        migrations.RenameField(
            model_name='allstopswithroute',
            old_name='stop_id',
            new_name='stop',
        ),
    ]
