# Generated by Django 3.2.4 on 2021-07-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('temp', models.CharField(max_length=10, null=True)),
                ('feels_like', models.CharField(max_length=45, null=True)),
                ('temp_min', models.CharField(max_length=45, null=True)),
                ('temp_max', models.CharField(max_length=45, null=True)),
                ('pressure', models.CharField(max_length=45, null=True)),
                ('humidity', models.CharField(max_length=45, null=True)),
                ('wind_speed', models.CharField(max_length=45, null=True)),
                ('wind_deg', models.CharField(max_length=45, null=True)),
                ('clouds_all', models.CharField(max_length=45, null=True)),
                ('weather_main', models.CharField(max_length=45, null=True)),
                ('weather_description', models.CharField(max_length=45, null=True)),
                ('weather_icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastWeather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dt_iso', models.CharField(max_length=45, null=True)),
                ('temp', models.CharField(max_length=45, null=True)),
                ('temp_min', models.CharField(max_length=45, null=True)),
                ('temp_max', models.CharField(max_length=45, null=True)),
                ('pressure', models.CharField(max_length=45, null=True)),
                ('humidity', models.CharField(max_length=45, null=True)),
                ('wind_speed', models.CharField(max_length=45, null=True)),
                ('wind_deg', models.CharField(max_length=45, null=True)),
                ('clouds_all', models.CharField(max_length=45, null=True)),
                ('weather_id', models.CharField(max_length=45, null=True)),
                ('weather_main', models.CharField(max_length=45, null=True)),
                ('weather_description', models.CharField(max_length=45, null=True)),
                ('weather_icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=45, null=True)),
                ('route_description', models.CharField(max_length=60, null=True)),
                ('route_direction', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops_second',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=45, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('stop_number', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllStopsWithRoute_second',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('stop_sequence', models.CharField(max_length=45, null=True)),
                ('stop_headsign', models.CharField(max_length=45, null=True)),
                ('route_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.routes_second')),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.stops_second')),
            ],
        ),
    ]
