# Generated by Django 3.2.4 on 2021-07-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllStopsWithRoute_second',
            new_name='AllStopsWithRoute',
        ),
        migrations.RenameModel(
            old_name='Routes_second',
            new_name='Routes',
        ),
        migrations.RenameModel(
            old_name='Stops_second',
            new_name='Stops',
        ),
    ]
