# Generated by Django 3.2.4 on 2021-07-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20210710_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastweather',
            name='dt',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='dt_iso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
