# Generated by Django 3.2.4 on 2021-07-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_auto_20210710_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastweather',
            name='dt_iso',
            field=models.DateTimeField(null=True),
        ),
    ]
