# Generated by Django 3.2.4 on 2021-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_alter_forecastweather_dt_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstopswithroute',
            name='direction',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
