# Generated by Django 3.2.4 on 2021-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_remove_allstopswithroute_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstopswithroute',
            name='direction',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
