# Generated by Django 3.2.4 on 2021-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0010_allstopswithroute_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('icu', models.CharField(max_length=45, null=True)),
                ('communityTransmission', models.CharField(max_length=45, null=True)),
                ('totalConfirmedCases', models.CharField(max_length=45, null=True)),
                ('totalDeaths', models.CharField(max_length=45, null=True)),
                ('confirmedCases', models.CharField(max_length=45, null=True)),
                ('confirmedDeaths', models.CharField(max_length=45, null=True)),
                ('closeContact', models.CharField(max_length=45, null=True)),
                ('statisticsProfileDt', models.CharField(max_length=45, null=True)),
                ('fid', models.CharField(max_length=45, null=True)),
                ('travelAbroad', models.CharField(max_length=45, null=True)),
                ('hospitalisedCases', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
