# Generated by Django 3.2.4 on 2021-07-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_remove_allstopswithroute_direction'),
        ('scrapper', '0013_auto_20210717_0647'),
    ]

    operations = [
    ]
