# Generated by Django 3.2.4 on 2021-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0014_merge_20210722_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstopswithroute',
            name='subRoute',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
