# Generated by Django 3.2.4 on 2021-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0015_auto_20210722_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePrediction',
            fields=[
                ('Route', models.CharField(max_length=10, null=True)),
                ('Direction', models.CharField(max_length=10, null=True)),
                ('StopOrder', models.CharField(max_length=10, null=True)),
                ('StopID', models.CharField(max_length=10, null=True)),
                ('PercentDone', models.CharField(max_length=10, null=True)),
                ('ID', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
    ]
