# Generated by Django 3.2.4 on 2021-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0016_auto_20210722_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=45, null=True)),
                ('start_time', models.CharField(max_length=45, null=True)),
                ('start_date', models.CharField(max_length=45, null=True)),
                ('trip_schedule', models.CharField(max_length=45, null=True)),
                ('stop_seq', models.CharField(max_length=45, null=True)),
                ('stop_delay', models.CharField(max_length=45, null=True)),
                ('stop_arrival', models.CharField(max_length=45, null=True)),
                ('stop_id', models.CharField(max_length=45, null=True)),
                ('stop_schedule', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
