# Generated by Django 3.2.4 on 2021-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0017_auto_20210727_0427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealTimeTraffic',
        ),
    ]
