# Generated by Django 3.2.4 on 2021-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0019_auto_20210727_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimetraffic',
            name='stop_seq',
        ),
    ]
