# Generated by Django 3.2.4 on 2021-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0020_auto_20210727_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=45, null=True)),
                ('agency_name', models.CharField(max_length=45, null=True)),
                ('agency_url', models.CharField(max_length=45, null=True)),
                ('agency_timezone', models.CharField(max_length=45, null=True)),
                ('agency_lang', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=45, null=True)),
                ('arrival_time', models.CharField(max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45, null=True)),
                ('stop_id', models.CharField(max_length=45, null=True)),
                ('stop_sequence', models.CharField(max_length=45, null=True)),
                ('stop_headsign', models.CharField(max_length=45, null=True)),
                ('pickup_type', models.CharField(max_length=45, null=True)),
                ('drop_off_type', models.CharField(max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=45, null=True)),
                ('service_id', models.CharField(max_length=45, null=True)),
                ('trip_id', models.CharField(max_length=45, null=True)),
                ('shape_id', models.CharField(max_length=45, null=True)),
                ('trip_headsign', models.CharField(max_length=45, null=True)),
                ('direction_id', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='allstopswithroute',
            name='direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='agency_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_id',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
