# Generated by Django 3.2.4 on 2021-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0021_auto_20210808_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='trip_headsign',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
