# Generated by Django 3.2.4 on 2021-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0022_alter_trips_trip_headsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=45, null=True)),
                ('arrival_time', models.CharField(max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45, null=True)),
                ('stop_id', models.CharField(max_length=45, null=True)),
                ('stop_sequence', models.CharField(max_length=45, null=True)),
                ('stop_headsign', models.CharField(max_length=45, null=True)),
                ('pickup_type', models.CharField(max_length=45, null=True)),
                ('drop_off_type', models.CharField(max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
